<a href="https://colab.research.google.com/github/Riyanshi243/Email_Spam_or_not/blob/main/Email_Spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [8]:
#load the dataset
from google.colab import files
uploaded=files.upload()

Saving spamham.csv to spamham.csv


In [9]:
#read the csv file
df=pd.read_csv('spamham.csv')
#print the first row
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [10]:
df.shape

(5728, 2)

In [12]:
df.columns

Index(['text', 'spam'], dtype='object')

In [17]:
#check for duplicates and remove
df.drop_duplicates(inplace=True)

In [30]:
df.shape

(5695, 2)

In [31]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [32]:
#download the stopward package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [33]:
#process text
def process_text(text):
    nopunch=[char for char in text if char not in string.punctuation]
    nopunch=''.join(nopunch)
    clean_words=[word for word in nopunch.split() if word.lower() not in stopwords.words('english')]
    return clean_words

In [34]:
#separating the words by comas as a list
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [36]:
#convert a collection of text to a matrix of token
from sklearn.feature_extraction.text import CountVectorizer
message_bow=CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [37]:
#split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(message_bow,df['spam'],test_size=0.20,random_state=0)

In [38]:
#get the shape of msg
message_bow.shape

(5695, 37229)

In [39]:
#create and train naive bayes classifier and multinomial naive bayes
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(X_train,y_train)

In [41]:
#print prediction
print(classifier.predict(X_train))
#print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [42]:
#evaluate the model (how good it is)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(X_train)
print( classification_report(y_train,pred))
print()
print('confusion Matrix:\n', confusion_matrix(y_train,pred))
print()
print('Accuracy  :',accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


confusion Matrix:
 [[3445   12]
 [   1 1098]]

Accuracy  : 0.9971466198419666


In [43]:
#print prediction
print(classifier.predict(X_test))
#print actual values
print(y_test.values)


[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [44]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(X_test)
print( classification_report(y_test,pred))
print()
print('confusion Matrix:\n', confusion_matrix(y_test,pred))
print()
print('Accuracy  :',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


confusion Matrix:
 [[862   8]
 [  1 268]]

Accuracy  : 0.9920983318700615
